### ISSUE TITLE
「新たな分散型SNS 「Pulsate」 について」内のリンク切れ

### ISSUE THREAD

**Issue by massongit** [m1sk9/blog#19]
https://blog.m1sk9.dev/posts/2023/about-pulsate 末尾にあるPulsate公式ホームページのリンクを押下すると、 `DNS_PROBE_FINISHED_NXDOMAIN` となってしまいます。
これでは戸惑ってしまうので、このリンクの削除 or 公式ホームページの正しいURLがあればそちらへの修正等していただけると良いかと思います。

**Comment by m1sk9** [comment]
Fixed #18

**Comment by massongit** [comment]
#18 は別の記事へのリンクを修正したものなので、本Issueで挙げているPulsate公式ホームページへのリンク切れはそれとは別の話になりますね。

**Comment by m1sk9** [comment]
> #18 は別の記事へのリンクを修正したものなので、本Issueで挙げているPulsate公式ホームページへのリンク切れはそれとは別の話になりますね。 コードでいうと以下になります。
> 
> https://github.com/m1sk9/blog/blob/7003569ef32d71eeea05e62560640eae4bd57e3e/src/pages/posts/2023/about-pulsate.md?plain=1#L64

あぁ. なるほど.
[公式サイト自体は現在開発中のため](https://github.com/pulsate-dev/pulsate.dev/)アクセスできないのは想定したものになりますが, 開発中であることを示す Plain Text を Cloudflare Worker でデプロイしたのでひとまずはアクセスできるようになるはずです.

**Comment by massongit** [comment]
>開発中であることを示す Plain Text を Cloudflare Worker でデプロイしたのでひとまずはアクセスできるようになるはずです.

こちら確認できました。
ありがとうございます。
